### ISSUE TITLE
Bug #2: TeamStat Model

### ISSUE THREAD

**Issue by BadDub** [glitch100/Halo-API#2]
TeamStat.Score should be an int, but the API currently returns an unsigned int. The HaloEzAPI wrapper model has the property as an int, so when an unsigned int that's too large for an int comes through, it explodes.
There's a bug, but whose?
On one hand, the API shouldn't be returning an unsigned int because score can be negative. On the other, the API currently does return an unsigned in, so the model should represent this.

https://github.com/glitch100/Halo-API/blob/master/HaloEzAPI/Model/Response/Stats/TeamStat.cs#L8
vs.

https://github.com/gitFurious/HaloSharp/blob/master/Source/HaloSharp/Model/Stats/CarnageReport/Common/TeamStat.cs#L12

**Comment by glitch100** [comment]
This has been fixed. Ultimately it is a problem with their API, as when testing it passes with some data, however in some scenarios, like the one you have seen their API _can_ return an unsigned int. Annoyingly I have no handling for this. I could change all usages of `int` to `uint` however it's overkill. 

I will change them as we find them. Thanks for creating the issue it has been fixed in 1.0.3 . Now available on [NuGet](https://www.nuget.org/packages/HaloEzAPI/1.0.3)
